//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.mirle.ibg3k0.ohxc.winform.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.mirle.ibg3k0.ohxc.winform.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Accel / Deccel Time 的當地語系化字串。
        /// </summary>
        internal static string Accel_Deccel_Time {
            get {
                return ResourceManager.GetString("Accel_Deccel_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Action 的當地語系化字串。
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Action__Cassette_ {
            get {
                object obj = ResourceManager.GetObject("Action__Cassette_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Action__Correcting_action_ {
            get {
                object obj = ResourceManager.GetObject("Action__Correcting_action_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Action__Loading_ {
            get {
                object obj = ResourceManager.GetObject("Action__Loading_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Action__Maintenance_ {
            get {
                object obj = ResourceManager.GetObject("Action__Maintenance_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Action__Moving_ {
            get {
                object obj = ResourceManager.GetObject("Action__Moving_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Action__Parked_ {
            get {
                object obj = ResourceManager.GetObject("Action__Parked_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Action__Parking_ {
            get {
                object obj = ResourceManager.GetObject("Action__Parking_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Action__Receive_command_ {
            get {
                object obj = ResourceManager.GetObject("Action__Receive_command_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Action__Unloading_ {
            get {
                object obj = ResourceManager.GetObject("Action__Unloading_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Address Data 的當地語系化字串。
        /// </summary>
        internal static string Address_Data {
            get {
                return ResourceManager.GetString("Address_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Address ID 的當地語系化字串。
        /// </summary>
        internal static string Address_ID {
            get {
                return ResourceManager.GetString("Address_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Alarm__Alert_ {
            get {
                object obj = ResourceManager.GetObject("Alarm__Alert_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Alarm__Error_ {
            get {
                object obj = ResourceManager.GetObject("Alarm__Error_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Alarm__Warning_ {
            get {
                object obj = ResourceManager.GetObject("Alarm__Warning_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 AREA SECSOR 的當地語系化字串。
        /// </summary>
        internal static string AREA_SECSOR {
            get {
                return ResourceManager.GetString("AREA_SECSOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Area Sensor-1 的當地語系化字串。
        /// </summary>
        internal static string Area_Sensor_1 {
            get {
                return ResourceManager.GetString("Area_Sensor_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Area Sensor-2 的當地語系化字串。
        /// </summary>
        internal static string Area_Sensor_2 {
            get {
                return ResourceManager.GetString("Area_Sensor_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Auto 的當地語系化字串。
        /// </summary>
        internal static string Auto {
            get {
                return ResourceManager.GetString("Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 BRANCH FLAG 的當地語系化字串。
        /// </summary>
        internal static string BRANCH_FLAG {
            get {
                return ResourceManager.GetString("BRANCH_FLAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CAN GUIDE CHG 的當地語系化字串。
        /// </summary>
        internal static string CAN_GUIDE_CHG {
            get {
                return ResourceManager.GetString("CAN_GUIDE_CHG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CDOG 1 的當地語系化字串。
        /// </summary>
        internal static string CDOG_1 {
            get {
                return ResourceManager.GetString("CDOG_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CDOG 2 的當地語系化字串。
        /// </summary>
        internal static string CDOG_2 {
            get {
                return ResourceManager.GetString("CDOG_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Change Stability Time 的當地語系化字串。
        /// </summary>
        internal static string Change_Stability_Time {
            get {
                return ResourceManager.GetString("Change_Stability_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Chart_Load {
            get {
                object obj = ResourceManager.GetObject("Chart_Load", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Chart_Unload {
            get {
                object obj = ResourceManager.GetObject("Chart_Unload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 CHG AREA SECSOR 1 的當地語系化字串。
        /// </summary>
        internal static string CHG_AREA_SECSOR_1 {
            get {
                return ResourceManager.GetString("CHG_AREA_SECSOR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CHG AREA SECSOR 2 的當地語系化字串。
        /// </summary>
        internal static string CHG_AREA_SECSOR_2 {
            get {
                return ResourceManager.GetString("CHG_AREA_SECSOR_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CHG SEG NUM 1 的當地語系化字串。
        /// </summary>
        internal static string CHG_SEG_NUM_1 {
            get {
                return ResourceManager.GetString("CHG_SEG_NUM_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CHG SEG NUM 2 的當地語系化字串。
        /// </summary>
        internal static string CHG_SEG_NUM_2 {
            get {
                return ResourceManager.GetString("CHG_SEG_NUM_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Collision Avoidance : Forward Straight 的當地語系化字串。
        /// </summary>
        internal static string Collision_Avoidance_Forward_Straight {
            get {
                return ResourceManager.GetString("Collision_Avoidance_Forward_Straight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Collision Avoidance : Left Straight 的當地語系化字串。
        /// </summary>
        internal static string Collision_Avoidance_Left_Straight {
            get {
                return ResourceManager.GetString("Collision_Avoidance_Left_Straight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Collision Avoidance : Right Straight 的當地語系化字串。
        /// </summary>
        internal static string Collision_Avoidance_Right_Straight {
            get {
                return ResourceManager.GetString("Collision_Avoidance_Right_Straight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Command: 的當地語系化字串。
        /// </summary>
        internal static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Connection_Control_Off {
            get {
                object obj = ResourceManager.GetObject("Connection_Control_Off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Connection_Control_On {
            get {
                object obj = ResourceManager.GetObject("Connection_Control_On", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Control Data 的當地語系化字串。
        /// </summary>
        internal static string Control_Data {
            get {
                return ResourceManager.GetString("Control_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Control Setting 的當地語系化字串。
        /// </summary>
        internal static string Control_Setting {
            get {
                return ResourceManager.GetString("Control_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Control_status_LinkFail {
            get {
                object obj = ResourceManager.GetObject("Control_status_LinkFail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Control_status_LinkOk {
            get {
                object obj = ResourceManager.GetObject("Control_status_LinkOk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 DIRC DRIV 的當地語系化字串。
        /// </summary>
        internal static string DIRC_DRIV {
            get {
                return ResourceManager.GetString("DIRC_DRIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 DIRC GUID 的當地語系化字串。
        /// </summary>
        internal static string DIRC_GUID {
            get {
                return ResourceManager.GetString("DIRC_GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Dircetion of Home 的當地語系化字串。
        /// </summary>
        internal static string Dircetion_of_Home {
            get {
                return ResourceManager.GetString("Dircetion_of_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Direction of Guide-1 的當地語系化字串。
        /// </summary>
        internal static string Direction_of_Guide_1 {
            get {
                return ResourceManager.GetString("Direction_of_Guide_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Direction of Guide-2 的當地語系化字串。
        /// </summary>
        internal static string Direction_of_Guide_2 {
            get {
                return ResourceManager.GetString("Direction_of_Guide_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Direction of Read 的當地語系化字串。
        /// </summary>
        internal static string Direction_of_Read {
            get {
                return ResourceManager.GetString("Direction_of_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Drive Dir. 的當地語系化字串。
        /// </summary>
        internal static string Drive_Dir {
            get {
                return ResourceManager.GetString("Drive_Dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enable Change Guide Area 的當地語系化字串。
        /// </summary>
        internal static string Enable_Change_Guide_Area {
            get {
                return ResourceManager.GetString("Enable_Change_Guide_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ENB CHG G AREA 的當地語系化字串。
        /// </summary>
        internal static string ENB_CHG_G_AREA {
            get {
                return ResourceManager.GetString("ENB_CHG_G_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 End BC 1 的當地語系化字串。
        /// </summary>
        internal static string END_BC1 {
            get {
                return ResourceManager.GetString("END_BC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 End BC 2 的當地語系化字串。
        /// </summary>
        internal static string END_BC2 {
            get {
                return ResourceManager.GetString("END_BC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 End BC 3 的當地語系化字串。
        /// </summary>
        internal static string END_BC3 {
            get {
                return ResourceManager.GetString("END_BC3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 From Address 的當地語系化字串。
        /// </summary>
        internal static string From_Address {
            get {
                return ResourceManager.GetString("From_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 From Adr. 的當地語系化字串。
        /// </summary>
        internal static string FROM_ADR_ID {
            get {
                return ResourceManager.GetString("FROM_ADR_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Front-Left Lock Position 的當地語系化字串。
        /// </summary>
        internal static string Front_Left_Lock_Position {
            get {
                return ResourceManager.GetString("Front_Left_Lock_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Front Limit 的當地語系化字串。
        /// </summary>
        internal static string Front_Limit {
            get {
                return ResourceManager.GetString("Front_Limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Front-Right Lock Position 的當地語系化字串。
        /// </summary>
        internal static string Front_Right_Lock_Position {
            get {
                return ResourceManager.GetString("Front_Right_Lock_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap FUU {
            get {
                object obj = ResourceManager.GetObject("FUU", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Guide Data 的當地語系化字串。
        /// </summary>
        internal static string Guide_Data {
            get {
                return ResourceManager.GetString("Guide_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Guide Dir. 的當地語系化字串。
        /// </summary>
        internal static string Guide_Dir {
            get {
                return ResourceManager.GetString("Guide_Dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 HID CONTROL 的當地語系化字串。
        /// </summary>
        internal static string HID_CONTROL {
            get {
                return ResourceManager.GetString("HID_CONTROL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Home Speed 的當地語系化字串。
        /// </summary>
        internal static string Home_Speed {
            get {
                return ResourceManager.GetString("Home_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_CSOTLogo {
            get {
                object obj = ResourceManager.GetObject("icon_CSOTLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_Hamburger {
            get {
                object obj = ResourceManager.GetObject("icon_Hamburger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_Home {
            get {
                object obj = ResourceManager.GetObject("icon_Home", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_MirleLogo {
            get {
                object obj = ResourceManager.GetObject("icon_MirleLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Inposition Area 的當地語系化字串。
        /// </summary>
        internal static string Inposition_Area {
            get {
                return ResourceManager.GetString("Inposition_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Inposition Stability Time 的當地語系化字串。
        /// </summary>
        internal static string Inposition_Stability_Time {
            get {
                return ResourceManager.GetString("Inposition_Stability_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 IS ADR RPT 的當地語系化字串。
        /// </summary>
        internal static string IS_ADR_RPT {
            get {
                return ResourceManager.GetString("IS_ADR_RPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Keep Distance - Far 的當地語系化字串。
        /// </summary>
        internal static string Keep_Distance_Far {
            get {
                return ResourceManager.GetString("Keep_Distance_Far", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Keep Distance - Near 的當地語系化字串。
        /// </summary>
        internal static string Keep_Distance_Near {
            get {
                return ResourceManager.GetString("Keep_Distance_Near", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Keep Distance Speed 的當地語系化字串。
        /// </summary>
        internal static string Keep_Distance_Speed {
            get {
                return ResourceManager.GetString("Keep_Distance_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Laser Sensor : Forward Straight 的當地語系化字串。
        /// </summary>
        internal static string Laser_Sensor_Forward_Straight {
            get {
                return ResourceManager.GetString("Laser_Sensor_Forward_Straight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Last Tech Time 的當地語系化字串。
        /// </summary>
        internal static string LAST_TECH_TIME {
            get {
                return ResourceManager.GetString("LAST_TECH_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Lifer_Down_1 {
            get {
                object obj = ResourceManager.GetObject("Lifer_Down_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Lifer_Down_2 {
            get {
                object obj = ResourceManager.GetObject("Lifer_Down_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Lifter 的當地語系化字串。
        /// </summary>
        internal static string Lifter {
            get {
                return ResourceManager.GetString("Lifter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Lifter Interlock 的當地語系化字串。
        /// </summary>
        internal static string Lifter_Interlock {
            get {
                return ResourceManager.GetString("Lifter_Interlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Lifter_Up_1 {
            get {
                object obj = ResourceManager.GetObject("Lifter_Up_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Lifter_Up_2 {
            get {
                object obj = ResourceManager.GetObject("Lifter_Up_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Lock 的當地語系化字串。
        /// </summary>
        internal static string Lock {
            get {
                return ResourceManager.GetString("Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Manual Command 的當地語系化字串。
        /// </summary>
        internal static string Manual_Command {
            get {
                return ResourceManager.GetString("Manual_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Maunual High Speed 的當地語系化字串。
        /// </summary>
        internal static string Maunual_High_Speed {
            get {
                return ResourceManager.GetString("Maunual_High_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Maunual Low Speed 的當地語系化字串。
        /// </summary>
        internal static string Maunual_Low_Speed {
            get {
                return ResourceManager.GetString("Maunual_Low_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Max Speed 的當地語系化字串。
        /// </summary>
        internal static string Max_Speed {
            get {
                return ResourceManager.GetString("Max_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Move to 的當地語系化字串。
        /// </summary>
        internal static string Move_to {
            get {
                return ResourceManager.GetString("Move_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap MTL_Down_Off {
            get {
                object obj = ResourceManager.GetObject("MTL_Down_Off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap MTL_Down_On {
            get {
                object obj = ResourceManager.GetObject("MTL_Down_On", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap MTL_green {
            get {
                object obj = ResourceManager.GetObject("MTL_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 MTL Mode: 的當地語系化字串。
        /// </summary>
        internal static string MTL_Mode {
            get {
                return ResourceManager.GetString("MTL_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap MTL_red {
            get {
                object obj = ResourceManager.GetObject("MTL_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap MTL_Up_Off {
            get {
                object obj = ResourceManager.GetObject("MTL_Up_Off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap MTL_Up_On {
            get {
                object obj = ResourceManager.GetObject("MTL_Up_On", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap MTS_green {
            get {
                object obj = ResourceManager.GetObject("MTS_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 MTS Interlock 的當地語系化字串。
        /// </summary>
        internal static string MTS_Interlock {
            get {
                return ResourceManager.GetString("MTS_Interlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MTS Mode: 的當地語系化字串。
        /// </summary>
        internal static string MTS_Mode {
            get {
                return ResourceManager.GetString("MTS_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap MTS_red {
            get {
                object obj = ResourceManager.GetObject("MTS_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 OBS Sensor 的當地語系化字串。
        /// </summary>
        internal static string OBS_SENSOR {
            get {
                return ResourceManager.GetString("OBS_SENSOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OBS SENSOR F 的當地語系化字串。
        /// </summary>
        internal static string OBS_SENSOR_F {
            get {
                return ResourceManager.GetString("OBS_SENSOR_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OBS SENSOR L 的當地語系化字串。
        /// </summary>
        internal static string OBS_SENSOR_L {
            get {
                return ResourceManager.GetString("OBS_SENSOR_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OBS SENSOR R 的當地語系化字串。
        /// </summary>
        internal static string OBS_SENSOR_R {
            get {
                return ResourceManager.GetString("OBS_SENSOR_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PADDING 的當地語系化字串。
        /// </summary>
        internal static string PADDING {
            get {
                return ResourceManager.GetString("PADDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Pause__Block_ {
            get {
                object obj = ResourceManager.GetObject("Pause__Block_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Pause__Earthquake_ {
            get {
                object obj = ResourceManager.GetObject("Pause__Earthquake_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Pause__HID_ {
            get {
                object obj = ResourceManager.GetObject("Pause__HID_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Pause__Obstructed_ {
            get {
                object obj = ResourceManager.GetObject("Pause__Obstructed_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Pause__Pause_ {
            get {
                object obj = ResourceManager.GetObject("Pause__Pause_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Pause__Safety_ {
            get {
                object obj = ResourceManager.GetObject("Pause__Safety_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Pole of Encoder 的當地語系化字串。
        /// </summary>
        internal static string Pole_of_Encoder {
            get {
                return ResourceManager.GetString("Pole_of_Encoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Position 的當地語系化字串。
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Pre Adr Report 的當地語系化字串。
        /// </summary>
        internal static string PRE_ADD_REPR {
            get {
                return ResourceManager.GetString("PRE_ADD_REPR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PRE BLO REQ 的當地語系化字串。
        /// </summary>
        internal static string PRE_BLO_REQ {
            get {
                return ResourceManager.GetString("PRE_BLO_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Pre Div 的當地語系化字串。
        /// </summary>
        internal static string PRE_DIV {
            get {
                return ResourceManager.GetString("PRE_DIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Presence Address Report 的當地語系化字串。
        /// </summary>
        internal static string Presence_Address_Report {
            get {
                return ResourceManager.GetString("Presence_Address_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Presence Blocking Request 的當地語系化字串。
        /// </summary>
        internal static string Presence_Blocking_Request {
            get {
                return ResourceManager.GetString("Presence_Blocking_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Presence Diverge 的當地語系化字串。
        /// </summary>
        internal static string Presence_Diverge {
            get {
                return ResourceManager.GetString("Presence_Diverge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Presence HID Control 的當地語系化字串。
        /// </summary>
        internal static string Presence_HID_Control {
            get {
                return ResourceManager.GetString("Presence_HID_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 RANGE SENSOR F 的當地語系化字串。
        /// </summary>
        internal static string RANGE_SENSOR_F {
            get {
                return ResourceManager.GetString("RANGE_SENSOR_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Rear-Left Lock Position 的當地語系化字串。
        /// </summary>
        internal static string Rear_Left_Lock_Position {
            get {
                return ResourceManager.GetString("Rear_Left_Lock_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Rear Limit 的當地語系化字串。
        /// </summary>
        internal static string Rear_Limit {
            get {
                return ResourceManager.GetString("Rear_Limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Rear-Right Lock Position 的當地語系化字串。
        /// </summary>
        internal static string Rear_Right_Lock_Position {
            get {
                return ResourceManager.GetString("Rear_Right_Lock_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Resolution 的當地語系化字串。
        /// </summary>
        internal static string Resolution {
            get {
                return ResourceManager.GetString("Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Running Speed 的當地語系化字串。
        /// </summary>
        internal static string Running_Speed {
            get {
                return ResourceManager.GetString("Running_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 S Curve Rate 的當地語系化字串。
        /// </summary>
        internal static string S_Curve_Rate {
            get {
                return ResourceManager.GetString("S_Curve_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Safty_door {
            get {
                object obj = ResourceManager.GetObject("Safty door", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Scale Data 的當地語系化字串。
        /// </summary>
        internal static string Scale_Data {
            get {
                return ResourceManager.GetString("Scale_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Scale Offset 的當地語系化字串。
        /// </summary>
        internal static string Scale_Offset {
            get {
                return ResourceManager.GetString("Scale_Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Scale Reset Distance 的當地語系化字串。
        /// </summary>
        internal static string Scale_Reset_Distance {
            get {
                return ResourceManager.GetString("Scale_Reset_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Sec Dir. 的當地語系化字串。
        /// </summary>
        internal static string SEC_DIR {
            get {
                return ResourceManager.GetString("SEC_DIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Sec Dis. 的當地語系化字串。
        /// </summary>
        internal static string SEC_DIS {
            get {
                return ResourceManager.GetString("SEC_DIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Section ID 的當地語系化字串。
        /// </summary>
        internal static string SEC_ID {
            get {
                return ResourceManager.GetString("SEC_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SEC ORDER NUM 的當地語系化字串。
        /// </summary>
        internal static string SEC_ORDER_NUM {
            get {
                return ResourceManager.GetString("SEC_ORDER_NUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Sec Speed 的當地語系化字串。
        /// </summary>
        internal static string SEC_SPD {
            get {
                return ResourceManager.GetString("SEC_SPD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Sec Type 的當地語系化字串。
        /// </summary>
        internal static string SEC_TYPE {
            get {
                return ResourceManager.GetString("SEC_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Section Data 的當地語系化字串。
        /// </summary>
        internal static string Section_Data {
            get {
                return ResourceManager.GetString("Section_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Section Distance 的當地語系化字串。
        /// </summary>
        internal static string Section_Distance {
            get {
                return ResourceManager.GetString("Section_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Section ID 的當地語系化字串。
        /// </summary>
        internal static string Section_ID {
            get {
                return ResourceManager.GetString("Section_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Section Speed 的當地語系化字串。
        /// </summary>
        internal static string Section_Speed {
            get {
                return ResourceManager.GetString("Section_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SEG NUM 的當地語系化字串。
        /// </summary>
        internal static string SEG_NUM {
            get {
                return ResourceManager.GetString("SEG_NUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Segment No. 的當地語系化字串。
        /// </summary>
        internal static string Segment_No {
            get {
                return ResourceManager.GetString("Segment_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Segment Number-1 的當地語系化字串。
        /// </summary>
        internal static string Segment_Number_1 {
            get {
                return ResourceManager.GetString("Segment_Number_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Segment Number-2 的當地語系化字串。
        /// </summary>
        internal static string Segment_Number_2 {
            get {
                return ResourceManager.GetString("Segment_Number_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Segment Reservation 的當地語系化字串。
        /// </summary>
        internal static string Segment_Reservation {
            get {
                return ResourceManager.GetString("Segment_Reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Sensor Setting 的當地語系化字串。
        /// </summary>
        internal static string Sensor_Setting {
            get {
                return ResourceManager.GetString("Sensor_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Sgment Detail 的當地語系化字串。
        /// </summary>
        internal static string Sgment_Detail {
            get {
                return ResourceManager.GetString("Sgment_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Speed__Fast_ {
            get {
                object obj = ResourceManager.GetObject("Speed__Fast_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Speed__Medium_ {
            get {
                object obj = ResourceManager.GetObject("Speed__Medium_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Speed__Slow_ {
            get {
                object obj = ResourceManager.GetObject("Speed__Slow_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Start BC 1 的當地語系化字串。
        /// </summary>
        internal static string START_BC1 {
            get {
                return ResourceManager.GetString("START_BC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Start BC 2 的當地語系化字串。
        /// </summary>
        internal static string START_BC2 {
            get {
                return ResourceManager.GetString("START_BC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Start BC 3 的當地語系化字串。
        /// </summary>
        internal static string START_BC3 {
            get {
                return ResourceManager.GetString("START_BC3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Start / Stop Speed 的當地語系化字串。
        /// </summary>
        internal static string Start_Stop_Speed {
            get {
                return ResourceManager.GetString("Start_Stop_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Control status_LinkOk.png 的當地語系化字串。
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Teaching Speed 的當地語系化字串。
        /// </summary>
        internal static string Teaching_Speed {
            get {
                return ResourceManager.GetString("Teaching_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Timeout of Blocking Response 的當地語系化字串。
        /// </summary>
        internal static string Timeout_of_Blocking_Response {
            get {
                return ResourceManager.GetString("Timeout_of_Blocking_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Timeout of T1 的當地語系化字串。
        /// </summary>
        internal static string Timeout_of_T1 {
            get {
                return ResourceManager.GetString("Timeout_of_T1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Timeout of T2 的當地語系化字串。
        /// </summary>
        internal static string Timeout_of_T2 {
            get {
                return ResourceManager.GetString("Timeout_of_T2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Timeout of T3 的當地語系化字串。
        /// </summary>
        internal static string Timeout_of_T3 {
            get {
                return ResourceManager.GetString("Timeout_of_T3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Timeout of T4 的當地語系化字串。
        /// </summary>
        internal static string Timeout_of_T4 {
            get {
                return ResourceManager.GetString("Timeout_of_T4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Timeout of T5 的當地語系化字串。
        /// </summary>
        internal static string Timeout_of_T5 {
            get {
                return ResourceManager.GetString("Timeout_of_T5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Timeout of T6 的當地語系化字串。
        /// </summary>
        internal static string Timeout_of_T6 {
            get {
                return ResourceManager.GetString("Timeout_of_T6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Timeout of T7 的當地語系化字串。
        /// </summary>
        internal static string Timeout_of_T7 {
            get {
                return ResourceManager.GetString("Timeout_of_T7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Timeout of T8 的當地語系化字串。
        /// </summary>
        internal static string Timeout_of_T8 {
            get {
                return ResourceManager.GetString("Timeout_of_T8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 To Address 的當地語系化字串。
        /// </summary>
        internal static string To_Address {
            get {
                return ResourceManager.GetString("To_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 To Adr. 的當地語系化字串。
        /// </summary>
        internal static string TO_ADR_ID {
            get {
                return ResourceManager.GetString("TO_ADR_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Total Pulse Of One Scale 的當地語系化字串。
        /// </summary>
        internal static string Total_Pulse_Of_One_Scale {
            get {
                return ResourceManager.GetString("Total_Pulse_Of_One_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Travel Base Data 的當地語系化字串。
        /// </summary>
        internal static string Travel_Base_Data {
            get {
                return ResourceManager.GetString("Travel_Base_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Travel Direction 的當地語系化字串。
        /// </summary>
        internal static string Travel_Direction {
            get {
                return ResourceManager.GetString("Travel_Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Type 的當地語系化字串。
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unlock 的當地語系化字串。
        /// </summary>
        internal static string Unlock {
            get {
                return ResourceManager.GetString("Unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Update Time :  的當地語系化字串。
        /// </summary>
        internal static string Update_Time {
            get {
                return ResourceManager.GetString("Update_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Update User :  的當地語系化字串。
        /// </summary>
        internal static string Update_User {
            get {
                return ResourceManager.GetString("Update_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Vehicle 的當地語系化字串。
        /// </summary>
        internal static string Vehicle {
            get {
                return ResourceManager.GetString("Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Vehicle__Auto_Local_ {
            get {
                object obj = ResourceManager.GetObject("Vehicle__Auto_Local_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Vehicle__Auto_Local__OHT {
            get {
                object obj = ResourceManager.GetObject("Vehicle__Auto_Local__OHT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Vehicle__Auto_Remote_ {
            get {
                object obj = ResourceManager.GetObject("Vehicle__Auto_Remote_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Vehicle__Auto_Remote__OHT {
            get {
                object obj = ResourceManager.GetObject("Vehicle__Auto_Remote__OHT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Vehicle__Manual_ {
            get {
                object obj = ResourceManager.GetObject("Vehicle__Manual_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Vehicle__Manual__OHT {
            get {
                object obj = ResourceManager.GetObject("Vehicle__Manual__OHT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Vehicle__Power_on_ {
            get {
                object obj = ResourceManager.GetObject("Vehicle__Power_on_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Vehicle__Power_on__OHT {
            get {
                object obj = ResourceManager.GetObject("Vehicle__Power_on__OHT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Vehicle__Unconnected_ {
            get {
                object obj = ResourceManager.GetObject("Vehicle__Unconnected_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Vehicle__Unconnected__OHT {
            get {
                object obj = ResourceManager.GetObject("Vehicle__Unconnected__OHT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Vehicle_display_V2_3 {
            get {
                object obj = ResourceManager.GetObject("Vehicle_display_V2_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Vehicle ID 的當地語系化字串。
        /// </summary>
        internal static string Vehicle_ID {
            get {
                return ResourceManager.GetString("Vehicle_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Vehicle Command 的當地語系化字串。
        /// </summary>
        internal static string Vehicle_Setting {
            get {
                return ResourceManager.GetString("Vehicle_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Vehicle Status 的當地語系化字串。
        /// </summary>
        internal static string Vehicle_Status {
            get {
                return ResourceManager.GetString("Vehicle_Status", resourceCulture);
            }
        }
    }
}
